### ISSUE TITLE
User Profile Creation

### ISSUE THREAD

**Issue by Cbeattie97** [alvin-est/dev-deploy#4]
Allow users to create and edit profiles focused on showcasing skills and projects.

Set up profile schema fields (e.g., bio, skills, project links).
Implement routes for creating and updating profiles.
Create frontend components for profile creation/editing.

**Comment by KateHanSta17** [comment]
@Cbeattie97 I created the registration form, from the homepage. 
@alvin-est has fixed the routing so the registration page opens correctly. It's working enough to view the UI.
@Tinaika19 has also worked on the profile page separately where users can add the additional profile data. 
I've given a list of profile skills we should add as pre-written options (in slack). I think we need to add this to the backend as well so the skills save against the user profile when selected and saved.

For now registration includes name, email and passwords. Profile editing will be done once a user has signed up and logged in. (T can show you!)
